version: "3"

services:
  domain:
    image: iagosrm/language-app-domain
    build: ./domain-web-api/
    ports:
      - "${PORT_DOMAIN}:${PORT_DOMAIN}"
    environment:
      - DATABASE_URL=${DATABASE_URL_DOMAIN}
      - PORT=${PORT_DOMAIN}

  auth:
    image: iagosrm/language-app-auth
    build: ./auth-web-api/
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    environment:
      - DATABASE_URL=${DATABASE_URL_AUTH}
      - PORT=${PORT_AUTH}

  postgres-auth:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_AUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_AUTH}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA_AUTH}
    volumes:
      - ${HOME}/language-app-auth-postgres-data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-domain:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DOMAIN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DOMAIN}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA_DOMAIN}
    volumes:
      - ${HOME}/language-app-domain-postgres-data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
