import {
  ISignUpAPIParams,
  ISignUpAPIResponse,
  SignUpHTTPDefinition,
  ISignInAPIParams,
  ISignInAPIResponse,
  SignInHTTPDefinition,
  SignOutHTTPDefinition,
  IGetUserAPIResponse,
  GetUserHTTPDefinition,
  IUpdateUserParams,
  IUpdateUserResponse,
  AuthUpdateUserHTTPDefinition,
  IVerifyAccountParams,
  VerifyAccountHTTPDefinition,
  UpdateProfileImageHTTPDefinition,
  IForgotPasswordParams,
  IForgotPasswordResponse,
  ForgotPasswordRequestHTTPDefinition,
  IResetPasswordParams,
  IResetPasswordResponse,
  ResetPasswordHTTPDefinition,
} from "@language-app/common-core";
import {
  GetActivitiesHTTPDefinition,
  IGetActivities,
  NewActivityHTTPDefinition,
  IPostActivity,
  GetActivityHTTPDefinition,
  IGetActivity,
  PostStudentOutputHTTPDefinition,
  IPostStudentOutput,
  GetStudentOutputsHTTPDefinition,
  IGetStudentOutputs,
  GetStudentOutputHTTPDefinition,
  IGetStudentOutput,
  InsertFeedbackToActivityHTTPDefinition,
  IPostFeedbackToOutput,
  InsertAssociationInvitationHTTPDefinition,
  INewAssociationInvitation,
  GetAssociationInvitationHTTPDefinition,
  IGetAssociationInvitation,
  EditAssociationInvitationHTTPDefinition,
  InsertActivityIntoStudentListHTTPDefinition,
  DeleteActivityFromStudentListHTTPDefinition,
  GetInstructorStudentsHTTPDefinition,
} from "@language-app/common-core";

// export const fetcherFactory = (fetcher) =>
export const signInFetcherFactory = (fetcher) => (args) =>
  fetcher[SignInHTTPDefinition.method](SignInHTTPDefinition.path, args);
