version: "3"

services:
  app:
    image: iagosrm/nodejs-poc
    build: .
    ports:
      - 3006:3006
    depends_on:
      postgres:
        condition: service_healthy
    # command: ["npm", "run", "dev"]
    tty: true
    volumes:
      - .:/app
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test
    volumes:
      - ${HOME}/nodejs-poc-postgres-data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
