name: Build & Test Auth API

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'packages/web-api-auth/**'
      - 'packages/common/**'

jobs:
  build_and_test:
    uses: 'iago-srm/language-app/.github/workflows/reusable-build-and-test.yml@main'
    with:
      package: 'web-api-auth'
