name: Perform E2E tests

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web-api/**'
      - 'packages/web-api-auth/**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Merge main -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: staging
          github_token: ${{ github.token }}

      - name: Integration tests
        working-directory: './packages/web-api'
        run: npm run tests:integration

      - name: Merge staging -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: production
          github_token: ${{ github.token }}
