name: Test WebApp

on:
  push:
    branches:
      - develop
    paths:
      - "packages/web-app/**"
      - "packages/common-core"

jobs:
  build_and_test:
    uses: "iago-srm/language-app/.github/workflows/reusable-build-and-test.yml@main"
    with:
      package: "web-app"
